import type { AssetType } from "./types";

/**
 * Reference list of well-known instruments. It powers the offline search, the
 * benchmark and market lists, and the simulated data mode (anchor prices,
 * volatility and dividend profile are rough orders of magnitude, never quotes).
 */

export type SessionId = "US" | "EU" | "UK" | "CH" | "DK" | "JP" | "HK" | "CRYPTO" | "FX" | "FUT";

export interface Session {
  tz: string;
  /** Minutes after local midnight. */
  open: number;
  close: number;
  /** Trades every day of the week. */
  everyDay?: boolean;
}

export const SESSIONS: Record<SessionId, Session> = {
  US: { tz: "America/New_York", open: 9 * 60 + 30, close: 16 * 60 },
  EU: { tz: "Europe/Paris", open: 9 * 60, close: 17 * 60 + 30 },
  UK: { tz: "Europe/London", open: 8 * 60, close: 16 * 60 + 30 },
  CH: { tz: "Europe/Zurich", open: 9 * 60, close: 17 * 60 + 30 },
  DK: { tz: "Europe/Copenhagen", open: 9 * 60, close: 17 * 60 },
  JP: { tz: "Asia/Tokyo", open: 9 * 60, close: 15 * 60 + 30 },
  HK: { tz: "Asia/Hong_Kong", open: 9 * 60 + 30, close: 16 * 60 },
  CRYPTO: { tz: "UTC", open: 0, close: 24 * 60, everyDay: true },
  FX: { tz: "Europe/London", open: 0, close: 24 * 60 },
  FUT: { tz: "America/New_York", open: 0, close: 23 * 60 },
};

export interface CatalogEntry {
  symbol: string;
  name: string;
  type: AssetType;
  currency: string;
  exchange: string;
  session: SessionId;
  /** Anchor price used by the simulator. */
  price: number;
  /** Annualized volatility and drift used by the simulator. */
  vol: number;
  drift: number;
  divYield?: number;
  /** Months (1–12) in which dividends go ex. */
  divMonths?: number[];
  sector?: string;
  industry?: string;
  country?: string;
  website?: string;
  employees?: number;
  marketCap?: number;
  pe?: number;
  description?: string;
  /** Exposure region for funds/indices. */
  region?: string;
  /** Eligible to the French PEA wrapper. */
  pea?: boolean;
}

const Q = [3, 6, 9, 12];
const Q2 = [2, 5, 8, 11];
const Q1 = [1, 4, 7, 10];

type Seed = Omit<CatalogEntry, "type" | "currency" | "exchange" | "session"> &
  Partial<Pick<CatalogEntry, "type" | "currency" | "exchange" | "session">>;

const us = (e: Seed): CatalogEntry => ({ type: "EQUITY", currency: "USD", exchange: "NASDAQ", session: "US", country: "États-Unis", ...e });
const nyse = (e: Seed): CatalogEntry => us({ exchange: "NYSE", ...e });
const paris = (e: Seed): CatalogEntry => ({
  type: "EQUITY",
  currency: "EUR",
  exchange: "Euronext Paris",
  session: "EU",
  country: "France",
  pea: true,
  ...e,
});
const eu = (e: Seed): CatalogEntry => ({ type: "EQUITY", currency: "EUR", session: "EU", exchange: "Europe", pea: true, ...e });
const etf = (e: Seed): CatalogEntry => ({ type: "ETF", currency: "EUR", exchange: "Euronext Paris", session: "EU", ...e });
const index = (e: Seed): CatalogEntry => ({ type: "INDEX", exchange: "Indice", ...e }) as CatalogEntry;
const fx = (symbol: string, name: string, price: number): CatalogEntry => ({
  symbol,
  name,
  type: "CURRENCY",
  currency: symbol.slice(3, 6),
  exchange: "Devises",
  session: "FX",
  price,
  vol: 0.07,
  drift: 0,
});
const future = (symbol: string, name: string, price: number, vol: number, currency = "USD"): CatalogEntry => ({
  symbol,
  name,
  type: "FUTURE",
  currency,
  exchange: "Contrats à terme",
  session: "FUT",
  price,
  vol,
  drift: 0.02,
});
const crypto = (symbol: string, name: string, price: number, vol: number, drift: number): CatalogEntry => ({
  symbol,
  name,
  type: "CRYPTOCURRENCY",
  currency: symbol.split("-")[1] ?? "USD",
  exchange: "Crypto",
  session: "CRYPTO",
  price,
  vol,
  drift,
  sector: "Crypto-actifs",
  country: "Monde",
});

export const CATALOG: CatalogEntry[] = [
  // ——— United States ———
  us({
    symbol: "AAPL",
    name: "Apple Inc.",
    price: 232,
    vol: 0.27,
    drift: 0.12,
    divYield: 0.0045,
    divMonths: Q2,
    sector: "Technology",
    industry: "Consumer Electronics",
    website: "https://www.apple.com",
    employees: 164000,
    marketCap: 3.45e12,
    pe: 35,
    description:
      "Apple conçoit et commercialise des smartphones (iPhone), ordinateurs (Mac), tablettes (iPad), objets connectés et services (App Store, iCloud, Apple Music, Apple Pay).",
  }),
  us({
    symbol: "MSFT",
    name: "Microsoft Corporation",
    price: 495,
    vol: 0.24,
    drift: 0.13,
    divYield: 0.007,
    divMonths: Q,
    sector: "Technology",
    industry: "Software - Infrastructure",
    website: "https://www.microsoft.com",
    employees: 228000,
    marketCap: 3.7e12,
    pe: 37,
    description:
      "Microsoft développe des logiciels (Windows, Office 365), des services cloud (Azure), du matériel (Surface, Xbox) et des outils d'intelligence artificielle.",
  }),
  us({
    symbol: "NVDA",
    name: "NVIDIA Corporation",
    price: 178,
    vol: 0.5,
    drift: 0.25,
    divYield: 0.0003,
    divMonths: Q,
    sector: "Technology",
    industry: "Semiconductors",
    website: "https://www.nvidia.com",
    employees: 36000,
    marketCap: 4.3e12,
    pe: 50,
    description:
      "NVIDIA conçoit des processeurs graphiques (GPU) et des plateformes de calcul accéléré, au cœur de l'IA, des centres de données et du jeu vidéo.",
  }),
  us({
    symbol: "GOOGL",
    name: "Alphabet Inc. (Classe A)",
    price: 245,
    vol: 0.3,
    drift: 0.14,
    divYield: 0.0035,
    divMonths: Q,
    sector: "Communication Services",
    industry: "Internet Content & Information",
    website: "https://abc.xyz",
    employees: 187000,
    marketCap: 2.9e12,
    pe: 26,
    description: "Alphabet est la maison mère de Google (recherche, YouTube, Android, Google Cloud) et de projets comme Waymo et Verily.",
  }),
  us({
    symbol: "AMZN",
    name: "Amazon.com, Inc.",
    price: 228,
    vol: 0.32,
    drift: 0.13,
    sector: "Consumer Cyclical",
    industry: "Internet Retail",
    website: "https://www.amazon.com",
    employees: 1550000,
    marketCap: 2.4e12,
    pe: 34,
    description:
      "Amazon exploite une place de marché en ligne mondiale, le cloud Amazon Web Services (AWS), la publicité et des services d'abonnement comme Prime.",
  }),
  us({
    symbol: "META",
    name: "Meta Platforms, Inc.",
    price: 720,
    vol: 0.38,
    drift: 0.15,
    divYield: 0.003,
    divMonths: Q,
    sector: "Communication Services",
    industry: "Internet Content & Information",
    website: "https://about.meta.com",
    employees: 76000,
    marketCap: 1.8e12,
    pe: 27,
    description:
      "Meta développe Facebook, Instagram, WhatsApp et Messenger, ainsi que des technologies de réalité virtuelle et augmentée (Reality Labs).",
  }),
  us({
    symbol: "TSLA",
    name: "Tesla, Inc.",
    price: 410,
    vol: 0.6,
    drift: 0.1,
    sector: "Consumer Cyclical",
    industry: "Auto Manufacturers",
    website: "https://www.tesla.com",
    employees: 125000,
    marketCap: 1.3e12,
    pe: 180,
    description: "Tesla conçoit et fabrique des véhicules électriques, des batteries de stockage d'énergie et des panneaux solaires.",
  }),
  nyse({
    symbol: "BRK-B",
    name: "Berkshire Hathaway Inc. (Classe B)",
    price: 490,
    vol: 0.17,
    drift: 0.1,
    sector: "Financial Services",
    industry: "Insurance - Diversified",
    website: "https://www.berkshirehathaway.com",
    employees: 392000,
    marketCap: 1.05e12,
    pe: 16,
    description:
      "Conglomérat dirigé historiquement par Warren Buffett, présent dans l'assurance (GEICO), le rail (BNSF), l'énergie et détenant un large portefeuille d'actions.",
  }),
  nyse({
    symbol: "V",
    name: "Visa Inc.",
    price: 345,
    vol: 0.2,
    drift: 0.11,
    divYield: 0.007,
    divMonths: Q2,
    sector: "Financial Services",
    industry: "Credit Services",
    website: "https://www.visa.com",
    employees: 31600,
    marketCap: 6.6e11,
    pe: 33,
    description:
      "Visa exploite l'un des plus grands réseaux de paiement électronique au monde, reliant consommateurs, commerçants et banques.",
  }),
  nyse({
    symbol: "MA",
    name: "Mastercard Incorporated",
    price: 575,
    vol: 0.21,
    drift: 0.12,
    divYield: 0.0052,
    divMonths: Q1,
    sector: "Financial Services",
    industry: "Credit Services",
    website: "https://www.mastercard.com",
    employees: 33400,
    marketCap: 5.3e11,
    pe: 38,
    description:
      "Mastercard est une entreprise technologique de paiement qui connecte consommateurs, institutions financières et commerçants dans plus de 200 pays.",
  }),
  nyse({
    symbol: "JPM",
    name: "JPMorgan Chase & Co.",
    price: 300,
    vol: 0.24,
    drift: 0.1,
    divYield: 0.019,
    divMonths: Q1,
    sector: "Financial Services",
    industry: "Banks - Diversified",
    website: "https://www.jpmorganchase.com",
    employees: 317000,
    marketCap: 8.3e11,
    pe: 15,
    description:
      "Première banque américaine par les actifs : banque de détail, banque d'investissement, gestion d'actifs et services aux entreprises.",
  }),
  nyse({
    symbol: "JNJ",
    name: "Johnson & Johnson",
    price: 178,
    vol: 0.16,
    drift: 0.05,
    divYield: 0.029,
    divMonths: [2, 5, 8, 11],
    sector: "Healthcare",
    industry: "Drug Manufacturers - General",
    website: "https://www.jnj.com",
    employees: 138000,
    marketCap: 4.3e11,
    pe: 19,
    description: "Groupe de santé diversifié, spécialisé dans les médicaments innovants et les technologies médicales.",
  }),
  nyse({
    symbol: "LLY",
    name: "Eli Lilly and Company",
    price: 820,
    vol: 0.34,
    drift: 0.18,
    divYield: 0.0075,
    divMonths: [2, 5, 8, 11],
    sector: "Healthcare",
    industry: "Drug Manufacturers - General",
    website: "https://www.lilly.com",
    employees: 47000,
    marketCap: 7.7e11,
    pe: 55,
    description: "Laboratoire pharmaceutique américain, leader des traitements contre le diabète et l'obésité (Mounjaro, Zepbound).",
  }),
  nyse({
    symbol: "KO",
    name: "The Coca-Cola Company",
    price: 69,
    vol: 0.14,
    drift: 0.05,
    divYield: 0.03,
    divMonths: [3, 6, 9, 11],
    sector: "Consumer Defensive",
    industry: "Beverages - Non-Alcoholic",
    website: "https://www.coca-colacompany.com",
    employees: 69700,
    marketCap: 3e11,
    pe: 24,
    description:
      "Premier fabricant mondial de boissons non alcoolisées, avec plus de 200 marques dont Coca-Cola, Fanta, Sprite et Minute Maid.",
  }),
  us({
    symbol: "PEP",
    name: "PepsiCo, Inc.",
    price: 146,
    vol: 0.16,
    drift: 0.04,
    divYield: 0.039,
    divMonths: [3, 6, 9, 12],
    sector: "Consumer Defensive",
    industry: "Beverages - Non-Alcoholic",
    website: "https://www.pepsico.com",
    employees: 318000,
    marketCap: 2e11,
    pe: 21,
    description: "Groupe agroalimentaire américain : boissons (Pepsi, Gatorade) et snacks (Lay's, Doritos, Quaker).",
  }),
  nyse({
    symbol: "PG",
    name: "The Procter & Gamble Company",
    price: 156,
    vol: 0.15,
    drift: 0.05,
    divYield: 0.027,
    divMonths: Q1,
    sector: "Consumer Defensive",
    industry: "Household & Personal Products",
    website: "https://www.pg.com",
    employees: 108000,
    marketCap: 3.7e11,
    pe: 24,
    description: "Leader mondial des produits de grande consommation : Pampers, Gillette, Ariel, Head & Shoulders, Oral-B.",
  }),
  nyse({
    symbol: "MCD",
    name: "McDonald's Corporation",
    price: 305,
    vol: 0.17,
    drift: 0.07,
    divYield: 0.024,
    divMonths: [2, 5, 8, 11],
    sector: "Consumer Cyclical",
    industry: "Restaurants",
    website: "https://www.mcdonalds.com",
    employees: 150000,
    marketCap: 2.2e11,
    pe: 26,
    description: "Première chaîne mondiale de restauration rapide, exploitée majoritairement en franchise.",
  }),
  us({
    symbol: "COST",
    name: "Costco Wholesale Corporation",
    price: 940,
    vol: 0.2,
    drift: 0.12,
    divYield: 0.005,
    divMonths: [2, 5, 8, 11],
    sector: "Consumer Defensive",
    industry: "Discount Stores",
    website: "https://www.costco.com",
    employees: 333000,
    marketCap: 4.2e11,
    pe: 52,
    description: "Exploitant d'entrepôts-clubs vendus sur abonnement, réputé pour ses prix bas et la fidélité de ses membres.",
  }),
  us({
    symbol: "AVGO",
    name: "Broadcom Inc.",
    price: 340,
    vol: 0.42,
    drift: 0.2,
    divYield: 0.007,
    divMonths: Q,
    sector: "Technology",
    industry: "Semiconductors",
    website: "https://www.broadcom.com",
    employees: 37000,
    marketCap: 1.6e12,
    pe: 60,
    description:
      "Concepteur de semi-conducteurs (réseaux, connectivité, puces sur mesure pour l'IA) et de logiciels d'infrastructure (VMware).",
  }),
  us({
    symbol: "AMD",
    name: "Advanced Micro Devices, Inc.",
    price: 165,
    vol: 0.5,
    drift: 0.12,
    sector: "Technology",
    industry: "Semiconductors",
    website: "https://www.amd.com",
    employees: 28000,
    marketCap: 2.7e11,
    pe: 95,
    description: "Concepteur de processeurs (Ryzen, EPYC) et de cartes graphiques (Radeon, Instinct) pour PC, serveurs et IA.",
  }),
  nyse({
    symbol: "ORCL",
    name: "Oracle Corporation",
    price: 230,
    vol: 0.38,
    drift: 0.14,
    divYield: 0.009,
    divMonths: Q1,
    sector: "Technology",
    industry: "Software - Infrastructure",
    website: "https://www.oracle.com",
    employees: 162000,
    marketCap: 6.5e11,
    pe: 52,
    description: "Éditeur de bases de données et de logiciels d'entreprise, fortement engagé dans le cloud (OCI) pour l'IA.",
  }),
  us({
    symbol: "NFLX",
    name: "Netflix, Inc.",
    price: 1150,
    vol: 0.36,
    drift: 0.15,
    sector: "Communication Services",
    industry: "Entertainment",
    website: "https://www.netflix.com",
    employees: 14000,
    marketCap: 4.9e11,
    pe: 48,
    description: "Premier service mondial de streaming vidéo par abonnement, avec plus de 300 millions de foyers abonnés.",
  }),
  us({
    symbol: "ADBE",
    name: "Adobe Inc.",
    price: 360,
    vol: 0.32,
    drift: 0.05,
    sector: "Technology",
    industry: "Software - Infrastructure",
    website: "https://www.adobe.com",
    employees: 30000,
    marketCap: 1.5e11,
    pe: 22,
    description: "Éditeur de logiciels de création (Photoshop, Premiere, Acrobat) et de solutions marketing numériques.",
  }),
  nyse({
    symbol: "CRM",
    name: "Salesforce, Inc.",
    price: 245,
    vol: 0.32,
    drift: 0.07,
    divYield: 0.0065,
    divMonths: [1, 4, 7, 10],
    sector: "Technology",
    industry: "Software - Application",
    website: "https://www.salesforce.com",
    employees: 76000,
    marketCap: 2.3e11,
    pe: 38,
    description: "Leader des logiciels de gestion de la relation client (CRM) en mode cloud.",
  }),
  nyse({
    symbol: "DIS",
    name: "The Walt Disney Company",
    price: 115,
    vol: 0.28,
    drift: 0.04,
    divYield: 0.009,
    divMonths: [1, 7],
    sector: "Communication Services",
    industry: "Entertainment",
    website: "https://www.thewaltdisneycompany.com",
    employees: 233000,
    marketCap: 2.1e11,
    pe: 18,
    description: "Groupe de divertissement : studios, parcs à thème, croisières, chaînes de télévision et Disney+.",
  }),
  nyse({
    symbol: "XOM",
    name: "Exxon Mobil Corporation",
    price: 114,
    vol: 0.24,
    drift: 0.04,
    divYield: 0.035,
    divMonths: [2, 5, 8, 11],
    sector: "Energy",
    industry: "Oil & Gas Integrated",
    website: "https://corporate.exxonmobil.com",
    employees: 61000,
    marketCap: 4.9e11,
    pe: 16,
    description: "Première compagnie pétrolière et gazière américaine, intégrée de l'exploration au raffinage et à la chimie.",
  }),
  nyse({
    symbol: "O",
    name: "Realty Income Corporation",
    price: 58,
    vol: 0.2,
    drift: 0.02,
    divYield: 0.055,
    divMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    sector: "Real Estate",
    industry: "REIT - Retail",
    website: "https://www.realtyincome.com",
    employees: 470,
    marketCap: 5.2e10,
    pe: 55,
    description:
      "Foncière américaine (REIT) surnommée « The Monthly Dividend Company », propriétaire de milliers de murs commerciaux loués à long terme.",
  }),
  nyse({
    symbol: "WMT",
    name: "Walmart Inc.",
    price: 102,
    vol: 0.18,
    drift: 0.12,
    divYield: 0.009,
    divMonths: [3, 5, 8, 12],
    sector: "Consumer Defensive",
    industry: "Discount Stores",
    website: "https://www.walmart.com",
    employees: 2100000,
    marketCap: 8.2e11,
    pe: 38,
    description: "Premier distributeur mondial, exploitant hypermarchés, supermarchés et une activité e-commerce en forte croissance.",
  }),
  nyse({
    symbol: "ABBV",
    name: "AbbVie Inc.",
    price: 225,
    vol: 0.22,
    drift: 0.08,
    divYield: 0.029,
    divMonths: [1, 4, 7, 10],
    sector: "Healthcare",
    industry: "Drug Manufacturers - General",
    website: "https://www.abbvie.com",
    employees: 55000,
    marketCap: 4e11,
    pe: 30,
    description: "Laboratoire biopharmaceutique spécialisé en immunologie (Skyrizi, Rinvoq), oncologie, neurosciences et esthétique.",
  }),
  us({
    symbol: "PLTR",
    name: "Palantir Technologies Inc.",
    price: 165,
    vol: 0.62,
    drift: 0.2,
    sector: "Technology",
    industry: "Software - Infrastructure",
    website: "https://www.palantir.com",
    employees: 3900,
    marketCap: 3.9e11,
    pe: 400,
    description: "Éditeur de plateformes d'analyse de données et d'IA pour les gouvernements et les entreprises.",
  }),

  // ——— France (Euronext Paris) ———
  paris({
    symbol: "MC.PA",
    name: "LVMH Moët Hennessy Louis Vuitton",
    price: 590,
    vol: 0.28,
    drift: 0.07,
    divYield: 0.022,
    divMonths: [4, 12],
    sector: "Consumer Cyclical",
    industry: "Luxury Goods",
    website: "https://www.lvmh.com",
    employees: 215000,
    marketCap: 2.95e11,
    pe: 24,
    description:
      "Numéro un mondial du luxe : mode et maroquinerie (Louis Vuitton, Dior), vins et spiritueux (Moët, Hennessy), parfums, montres et joaillerie (Tiffany, Bulgari), distribution sélective (Sephora).",
  }),
  paris({
    symbol: "OR.PA",
    name: "L'Oréal S.A.",
    price: 372,
    vol: 0.21,
    drift: 0.07,
    divYield: 0.019,
    divMonths: [4],
    sector: "Consumer Defensive",
    industry: "Household & Personal Products",
    website: "https://www.loreal.com",
    employees: 90000,
    marketCap: 2e11,
    pe: 31,
    description:
      "Numéro un mondial de la beauté : produits grand public (L'Oréal Paris, Garnier), luxe (Lancôme, YSL Beauté), dermatologie (La Roche-Posay, CeraVe).",
  }),
  paris({
    symbol: "RMS.PA",
    name: "Hermès International",
    price: 2150,
    vol: 0.27,
    drift: 0.12,
    divYield: 0.008,
    divMonths: [5],
    sector: "Consumer Cyclical",
    industry: "Luxury Goods",
    website: "https://www.hermes.com",
    employees: 23000,
    marketCap: 2.27e11,
    pe: 50,
    description:
      "Maison de luxe française fondée en 1837, célèbre pour sa maroquinerie (Birkin, Kelly), ses carrés de soie et son savoir-faire artisanal.",
  }),
  paris({
    symbol: "AI.PA",
    name: "Air Liquide",
    price: 172,
    vol: 0.17,
    drift: 0.08,
    divYield: 0.019,
    divMonths: [5],
    sector: "Basic Materials",
    industry: "Specialty Chemicals",
    website: "https://www.airliquide.com",
    employees: 66000,
    marketCap: 9.9e10,
    pe: 29,
    description:
      "Leader mondial des gaz, technologies et services pour l'industrie et la santé, réputé pour la régularité de son dividende et ses actions gratuites.",
  }),
  paris({
    symbol: "TTE.PA",
    name: "TotalEnergies SE",
    price: 54,
    vol: 0.22,
    drift: 0.03,
    divYield: 0.063,
    divMonths: [1, 3, 6, 9],
    sector: "Energy",
    industry: "Oil & Gas Integrated",
    website: "https://totalenergies.com",
    employees: 102000,
    marketCap: 1.2e11,
    pe: 9,
    description:
      "Major intégrée de l'énergie : pétrole, gaz naturel liquéfié, électricité et renouvelables, présente dans plus de 120 pays.",
  }),
  paris({
    symbol: "SAN.PA",
    name: "Sanofi",
    price: 88,
    vol: 0.19,
    drift: 0.03,
    divYield: 0.044,
    divMonths: [5],
    sector: "Healthcare",
    industry: "Drug Manufacturers - General",
    website: "https://www.sanofi.com",
    employees: 82000,
    marketCap: 1.08e11,
    pe: 14,
    description: "Groupe biopharmaceutique français : immunologie (Dupixent), vaccins, maladies rares et santé grand public.",
  }),
  paris({
    symbol: "SU.PA",
    name: "Schneider Electric SE",
    price: 232,
    vol: 0.26,
    drift: 0.12,
    divYield: 0.017,
    divMonths: [5],
    sector: "Industrials",
    industry: "Specialty Industrial Machinery",
    website: "https://www.se.com",
    employees: 150000,
    marketCap: 1.3e11,
    pe: 30,
    description:
      "Spécialiste de la gestion de l'énergie et des automatismes : bâtiments, centres de données, industrie et infrastructures.",
  }),
  paris({
    symbol: "AIR.PA",
    name: "Airbus SE",
    price: 205,
    vol: 0.27,
    drift: 0.1,
    divYield: 0.011,
    divMonths: [4],
    sector: "Industrials",
    industry: "Aerospace & Defense",
    website: "https://www.airbus.com",
    employees: 157000,
    marketCap: 1.62e11,
    pe: 30,
    description: "Constructeur aéronautique européen : avions commerciaux (A320, A350), hélicoptères, défense et espace.",
  }),
  paris({
    symbol: "BNP.PA",
    name: "BNP Paribas",
    price: 76,
    vol: 0.27,
    drift: 0.07,
    divYield: 0.065,
    divMonths: [5],
    sector: "Financial Services",
    industry: "Banks - Diversified",
    website: "https://group.bnpparibas",
    employees: 178000,
    marketCap: 8.6e10,
    pe: 7,
    description:
      "Première banque de la zone euro : banque de détail, banque de financement et d'investissement, assurance et gestion d'actifs.",
  }),
  paris({
    symbol: "SAF.PA",
    name: "Safran",
    price: 290,
    vol: 0.27,
    drift: 0.14,
    divYield: 0.01,
    divMonths: [5],
    sector: "Industrials",
    industry: "Aerospace & Defense",
    website: "https://www.safran-group.com",
    employees: 100000,
    marketCap: 1.2e11,
    pe: 32,
    description:
      "Équipementier aéronautique de premier plan : moteurs d'avions (CFM avec GE), trains d'atterrissage, intérieurs de cabine et défense.",
  }),
  paris({
    symbol: "DG.PA",
    name: "Vinci",
    price: 118,
    vol: 0.19,
    drift: 0.07,
    divYield: 0.04,
    divMonths: [4, 11],
    sector: "Industrials",
    industry: "Engineering & Construction",
    website: "https://www.vinci.com",
    employees: 285000,
    marketCap: 6.8e10,
    pe: 14,
    description: "Leader mondial des concessions (autoroutes, aéroports) et de la construction, également présent dans l'énergie.",
  }),
  paris({
    symbol: "EL.PA",
    name: "EssilorLuxottica",
    price: 275,
    vol: 0.2,
    drift: 0.1,
    divYield: 0.014,
    divMonths: [5],
    sector: "Healthcare",
    industry: "Medical Instruments & Supplies",
    website: "https://www.essilorluxottica.com",
    employees: 200000,
    marketCap: 1.25e11,
    pe: 45,
    description:
      "Leader mondial de l'optique : verres (Varilux), montures et lunettes de soleil (Ray-Ban, Oakley) et distribution (Sunglass Hut).",
  }),
  paris({
    symbol: "CAP.PA",
    name: "Capgemini SE",
    price: 135,
    vol: 0.3,
    drift: 0.04,
    divYield: 0.025,
    divMonths: [5],
    sector: "Technology",
    industry: "Information Technology Services",
    website: "https://www.capgemini.com",
    employees: 340000,
    marketCap: 2.3e10,
    pe: 13,
    description: "Groupe de conseil, services informatiques et transformation numérique, parmi les leaders mondiaux du secteur.",
  }),
  paris({
    symbol: "KER.PA",
    name: "Kering",
    price: 260,
    vol: 0.38,
    drift: 0.0,
    divYield: 0.02,
    divMonths: [1, 5],
    sector: "Consumer Cyclical",
    industry: "Luxury Goods",
    website: "https://www.kering.com",
    employees: 47000,
    marketCap: 3.2e10,
    pe: 28,
    description: "Groupe de luxe regroupant Gucci, Saint Laurent, Bottega Veneta, Balenciaga et Kering Eyewear.",
  }),
  paris({
    symbol: "RI.PA",
    name: "Pernod Ricard",
    price: 88,
    vol: 0.24,
    drift: -0.02,
    divYield: 0.052,
    divMonths: [7, 11],
    sector: "Consumer Defensive",
    industry: "Beverages - Wineries & Distilleries",
    website: "https://www.pernod-ricard.com",
    employees: 19000,
    marketCap: 2.2e10,
    pe: 14,
    description: "Numéro deux mondial des vins et spiritueux : Absolut, Jameson, Chivas Regal, Ricard, Martell, Mumm.",
  }),
  paris({
    symbol: "CS.PA",
    name: "AXA",
    price: 41,
    vol: 0.21,
    drift: 0.08,
    divYield: 0.055,
    divMonths: [5],
    sector: "Financial Services",
    industry: "Insurance - Diversified",
    website: "https://www.axa.com",
    employees: 154000,
    marketCap: 8.9e10,
    pe: 11,
    description: "Leader mondial de l'assurance et de la gestion d'actifs, présent dans une cinquantaine de pays.",
  }),
  paris({
    symbol: "BN.PA",
    name: "Danone",
    price: 71,
    vol: 0.16,
    drift: 0.05,
    divYield: 0.03,
    divMonths: [5],
    sector: "Consumer Defensive",
    industry: "Packaged Foods",
    website: "https://www.danone.com",
    employees: 90000,
    marketCap: 4.6e10,
    pe: 20,
    description: "Groupe agroalimentaire : produits laitiers et d'origine végétale, eaux (Evian, Volvic) et nutrition spécialisée.",
  }),
  paris({
    symbol: "DSY.PA",
    name: "Dassault Systèmes",
    price: 29,
    vol: 0.3,
    drift: 0.02,
    divYield: 0.009,
    divMonths: [5],
    sector: "Technology",
    industry: "Software - Application",
    website: "https://www.3ds.com",
    employees: 26000,
    marketCap: 3.8e10,
    pe: 30,
    description: "Éditeur de logiciels de conception 3D, de simulation et de gestion du cycle de vie des produits (CATIA, SOLIDWORKS).",
  }),
  paris({
    symbol: "ORA.PA",
    name: "Orange",
    price: 14.2,
    vol: 0.18,
    drift: 0.04,
    divYield: 0.053,
    divMonths: [6, 12],
    sector: "Communication Services",
    industry: "Telecom Services",
    website: "https://www.orange.com",
    employees: 127000,
    marketCap: 3.8e10,
    pe: 16,
    description: "Opérateur historique français de télécommunications, présent en Europe, en Afrique et au Moyen-Orient.",
  }),
  paris({
    symbol: "ENGI.PA",
    name: "Engie",
    price: 19.5,
    vol: 0.2,
    drift: 0.05,
    divYield: 0.07,
    divMonths: [5],
    sector: "Utilities",
    industry: "Utilities - Diversified",
    website: "https://www.engie.com",
    employees: 97000,
    marketCap: 4.7e10,
    pe: 9,
    description: "Groupe énergétique : production d'électricité bas carbone, réseaux gaziers, renouvelables et services énergétiques.",
  }),
  paris({
    symbol: "GLE.PA",
    name: "Société Générale",
    price: 56,
    vol: 0.34,
    drift: 0.12,
    divYield: 0.03,
    divMonths: [5],
    sector: "Financial Services",
    industry: "Banks - Diversified",
    website: "https://www.societegenerale.com",
    employees: 119000,
    marketCap: 4.4e10,
    pe: 9,
    description: "Groupe bancaire européen : banque de détail en France et à l'international, banque de financement et d'investissement.",
  }),
  paris({
    symbol: "ACA.PA",
    name: "Crédit Agricole S.A.",
    price: 16.5,
    vol: 0.24,
    drift: 0.07,
    divYield: 0.068,
    divMonths: [5],
    sector: "Financial Services",
    industry: "Banks - Regional",
    website: "https://www.credit-agricole.com",
    employees: 78000,
    marketCap: 5e10,
    pe: 8,
    description:
      "Filiale cotée du groupe Crédit Agricole : banque de détail (LCL), assurance, gestion d'actifs (Amundi) et banque de financement.",
  }),
  paris({
    symbol: "SGO.PA",
    name: "Compagnie de Saint-Gobain",
    price: 96,
    vol: 0.27,
    drift: 0.1,
    divYield: 0.023,
    divMonths: [6],
    sector: "Industrials",
    industry: "Building Products & Equipment",
    website: "https://www.saint-gobain.com",
    employees: 160000,
    marketCap: 4.8e10,
    pe: 16,
    description: "Leader mondial de la construction légère et durable : vitrage, isolation, plâtre, mortiers et distribution de matériaux.",
  }),
  paris({
    symbol: "VIE.PA",
    name: "Veolia Environnement",
    price: 29,
    vol: 0.19,
    drift: 0.05,
    divYield: 0.047,
    divMonths: [5],
    sector: "Utilities",
    industry: "Utilities - Diversified",
    website: "https://www.veolia.com",
    employees: 215000,
    marketCap: 2.1e10,
    pe: 20,
    description: "Numéro un mondial de la transformation écologique : gestion de l'eau, des déchets et de l'énergie.",
  }),
  paris({
    symbol: "HO.PA",
    name: "Thales",
    price: 245,
    vol: 0.28,
    drift: 0.14,
    divYield: 0.015,
    divMonths: [5, 12],
    sector: "Industrials",
    industry: "Aerospace & Defense",
    website: "https://www.thalesgroup.com",
    employees: 81000,
    marketCap: 5e10,
    pe: 30,
    description: "Groupe technologique de défense, d'aérospatial, de cybersécurité et d'identité numérique.",
  }),
  paris({
    symbol: "STLAP.PA",
    name: "Stellantis N.V.",
    price: 8.9,
    vol: 0.4,
    drift: -0.05,
    divYield: 0.08,
    divMonths: [4],
    sector: "Consumer Cyclical",
    industry: "Auto Manufacturers",
    website: "https://www.stellantis.com",
    employees: 248000,
    marketCap: 2.6e10,
    pe: 12,
    description: "Constructeur automobile né de la fusion de PSA et Fiat Chrysler : Peugeot, Citroën, Fiat, Jeep, Opel, Ram.",
  }),
  paris({
    symbol: "RNO.PA",
    name: "Renault",
    price: 38,
    vol: 0.34,
    drift: 0.05,
    divYield: 0.058,
    divMonths: [5],
    sector: "Consumer Cyclical",
    industry: "Auto Manufacturers",
    website: "https://www.renaultgroup.com",
    employees: 105000,
    marketCap: 1.1e10,
    pe: 6,
    description: "Constructeur automobile français : Renault, Dacia, Alpine et services de mobilité.",
  }),

  // ——— Europe ———
  eu({
    symbol: "ASML.AS",
    name: "ASML Holding N.V.",
    exchange: "Euronext Amsterdam",
    country: "Pays-Bas",
    price: 720,
    vol: 0.37,
    drift: 0.13,
    divYield: 0.009,
    divMonths: [2, 4, 7, 10],
    sector: "Technology",
    industry: "Semiconductor Equipment & Materials",
    website: "https://www.asml.com",
    employees: 44000,
    marketCap: 2.8e11,
    pe: 32,
    description: "Fournisseur exclusif des machines de lithographie EUV indispensables à la fabrication des puces les plus avancées.",
  }),
  eu({
    symbol: "SAP.DE",
    name: "SAP SE",
    exchange: "Xetra",
    country: "Allemagne",
    price: 238,
    vol: 0.27,
    drift: 0.14,
    divYield: 0.01,
    divMonths: [5],
    sector: "Technology",
    industry: "Software - Application",
    website: "https://www.sap.com",
    employees: 108000,
    marketCap: 2.8e11,
    pe: 45,
    description: "Premier éditeur européen de logiciels : progiciels de gestion intégrés (ERP) et solutions cloud pour les entreprises.",
  }),
  eu({
    symbol: "SIE.DE",
    name: "Siemens AG",
    exchange: "Xetra",
    country: "Allemagne",
    price: 225,
    vol: 0.24,
    drift: 0.1,
    divYield: 0.023,
    divMonths: [2],
    sector: "Industrials",
    industry: "Specialty Industrial Machinery",
    website: "https://www.siemens.com",
    employees: 312000,
    marketCap: 1.8e11,
    pe: 20,
    description: "Conglomérat technologique allemand : automatisation industrielle, infrastructures intelligentes, mobilité et santé.",
  }),
  eu({
    symbol: "ALV.DE",
    name: "Allianz SE",
    exchange: "Xetra",
    country: "Allemagne",
    price: 355,
    vol: 0.19,
    drift: 0.09,
    divYield: 0.043,
    divMonths: [5],
    sector: "Financial Services",
    industry: "Insurance - Diversified",
    website: "https://www.allianz.com",
    employees: 157000,
    marketCap: 1.37e11,
    pe: 13,
    description: "Assureur et gestionnaire d'actifs allemand (PIMCO, Allianz Global Investors), parmi les plus grands au monde.",
  }),
  eu({
    symbol: "RACE.MI",
    name: "Ferrari N.V.",
    exchange: "Borsa Italiana",
    country: "Italie",
    price: 400,
    vol: 0.27,
    drift: 0.12,
    divYield: 0.008,
    divMonths: [4],
    sector: "Consumer Cyclical",
    industry: "Auto Manufacturers",
    website: "https://www.ferrari.com",
    employees: 5000,
    marketCap: 7.2e10,
    pe: 45,
    description: "Constructeur italien de voitures de sport et de luxe, également engagé en Formule 1 (Scuderia Ferrari).",
  }),
  eu({
    symbol: "ITX.MC",
    name: "Industria de Diseño Textil, S.A.",
    exchange: "Bolsa de Madrid",
    country: "Espagne",
    price: 46,
    vol: 0.24,
    drift: 0.1,
    divYield: 0.033,
    divMonths: [5, 11],
    sector: "Consumer Cyclical",
    industry: "Apparel Retail",
    website: "https://www.inditex.com",
    employees: 165000,
    marketCap: 1.43e11,
    pe: 23,
    description: "Premier groupe mondial de prêt-à-porter : Zara, Massimo Dutti, Pull&Bear, Bershka, Stradivarius.",
  }),
  {
    symbol: "NESN.SW",
    name: "Nestlé S.A.",
    type: "EQUITY",
    currency: "CHF",
    exchange: "SIX Swiss",
    session: "CH",
    country: "Suisse",
    price: 80,
    vol: 0.16,
    drift: 0.02,
    divYield: 0.038,
    divMonths: [4],
    sector: "Consumer Defensive",
    industry: "Packaged Foods",
    website: "https://www.nestle.com",
    employees: 277000,
    marketCap: 2.1e11,
    pe: 18,
    description: "Premier groupe agroalimentaire mondial : Nescafé, Nespresso, KitKat, Purina, Maggi, Perrier.",
  },
  {
    symbol: "NOVO-B.CO",
    name: "Novo Nordisk A/S",
    type: "EQUITY",
    currency: "DKK",
    exchange: "Nasdaq Copenhagen",
    session: "DK",
    country: "Danemark",
    pea: true,
    price: 360,
    vol: 0.4,
    drift: 0.05,
    divYield: 0.03,
    divMonths: [3, 8],
    sector: "Healthcare",
    industry: "Biotechnology",
    website: "https://www.novonordisk.com",
    employees: 77000,
    marketCap: 1.6e12,
    pe: 16,
    description: "Laboratoire danois leader des traitements du diabète et de l'obésité (Ozempic, Wegovy).",
  },
  {
    symbol: "SHEL.L",
    name: "Shell plc",
    type: "EQUITY",
    currency: "GBp",
    exchange: "London Stock Exchange",
    session: "UK",
    country: "Royaume-Uni",
    price: 2750,
    vol: 0.22,
    drift: 0.04,
    divYield: 0.04,
    divMonths: [2, 5, 8, 11],
    sector: "Energy",
    industry: "Oil & Gas Integrated",
    website: "https://www.shell.com",
    employees: 96000,
    marketCap: 1.65e11,
    pe: 13,
    description: "Major pétrolière et gazière britannique, premier acteur mondial du gaz naturel liquéfié.",
  },
  {
    symbol: "AZN.L",
    name: "AstraZeneca PLC",
    type: "EQUITY",
    currency: "GBp",
    exchange: "London Stock Exchange",
    session: "UK",
    country: "Royaume-Uni",
    price: 11800,
    vol: 0.22,
    drift: 0.07,
    divYield: 0.02,
    divMonths: [2, 8],
    sector: "Healthcare",
    industry: "Drug Manufacturers - General",
    website: "https://www.astrazeneca.com",
    employees: 94000,
    marketCap: 1.83e11,
    pe: 30,
    description: "Laboratoire biopharmaceutique anglo-suédois : oncologie, maladies cardiovasculaires, rénales et respiratoires.",
  },

  // ——— ETFs ———
  etf({
    symbol: "CW8.PA",
    name: "Amundi MSCI World UCITS ETF - EUR (C)",
    price: 580,
    vol: 0.14,
    drift: 0.085,
    region: "Monde",
    pea: true,
    sector: "Actions internationales",
    website: "https://www.amundietf.fr",
    description:
      "ETF capitalisant répliquant l'indice MSCI World (≈1 500 grandes et moyennes capitalisations de 23 pays développés), éligible au PEA.",
  }),
  etf({
    symbol: "EWLD.PA",
    name: "Amundi PEA Monde (MSCI World) UCITS ETF",
    price: 34,
    vol: 0.14,
    drift: 0.085,
    region: "Monde",
    pea: true,
    sector: "Actions internationales",
    website: "https://www.amundietf.fr",
    description: "ETF capitalisant exposé au MSCI World via un panier éligible au PEA et un swap de performance.",
  }),
  etf({
    symbol: "ESE.PA",
    name: "BNP Paribas Easy S&P 500 UCITS ETF EUR C",
    price: 29,
    vol: 0.16,
    drift: 0.1,
    region: "États-Unis",
    pea: true,
    sector: "Actions américaines",
    website: "https://www.easy.bnpparibas.fr",
    description: "ETF capitalisant répliquant l'indice S&P 500 des 500 plus grandes entreprises américaines, éligible au PEA.",
  }),
  etf({
    symbol: "PANX.PA",
    name: "Amundi PEA Nasdaq-100 UCITS ETF",
    price: 82,
    vol: 0.22,
    drift: 0.13,
    region: "États-Unis",
    pea: true,
    sector: "Actions américaines",
    website: "https://www.amundietf.fr",
    description: "ETF capitalisant exposé à l'indice Nasdaq-100 (grandes valeurs technologiques américaines), éligible au PEA.",
  }),
  etf({
    symbol: "PAEEM.PA",
    name: "Amundi PEA MSCI Emerging Markets UCITS ETF",
    price: 26,
    vol: 0.16,
    drift: 0.06,
    region: "Pays émergents",
    pea: true,
    sector: "Actions émergentes",
    website: "https://www.amundietf.fr",
    description: "ETF capitalisant exposé à l'indice MSCI Emerging Markets (Chine, Inde, Taïwan, Corée…), éligible au PEA.",
  }),
  etf({
    symbol: "C40.PA",
    name: "Amundi CAC 40 UCITS ETF Dist",
    price: 130,
    vol: 0.17,
    drift: 0.05,
    divYield: 0.028,
    divMonths: [12],
    region: "France",
    pea: true,
    sector: "Actions françaises",
    website: "https://www.amundietf.fr",
    description: "ETF distribuant répliquant l'indice CAC 40 des 40 principales capitalisations de la Bourse de Paris.",
  }),
  etf({
    symbol: "IWDA.AS",
    name: "iShares Core MSCI World UCITS ETF USD (Acc)",
    exchange: "Euronext Amsterdam",
    price: 106,
    vol: 0.14,
    drift: 0.085,
    region: "Monde",
    sector: "Actions internationales",
    website: "https://www.ishares.com",
    description: "ETF capitalisant parmi les plus importants d'Europe, répliquant physiquement l'indice MSCI World.",
  }),
  etf({
    symbol: "VWCE.DE",
    name: "Vanguard FTSE All-World UCITS ETF (USD) Acc",
    exchange: "Xetra",
    price: 138,
    vol: 0.14,
    drift: 0.08,
    region: "Monde",
    sector: "Actions internationales",
    website: "https://www.vanguard.fr",
    description: "ETF capitalisant répliquant l'indice FTSE All-World : ≈4 000 entreprises des pays développés et émergents.",
  }),
  etf({
    symbol: "SXR8.DE",
    name: "iShares Core S&P 500 UCITS ETF USD (Acc)",
    exchange: "Xetra",
    price: 610,
    vol: 0.16,
    drift: 0.1,
    region: "États-Unis",
    sector: "Actions américaines",
    website: "https://www.ishares.com",
    description: "ETF capitalisant répliquant physiquement l'indice S&P 500, coté en euros sur Xetra.",
  }),
  etf({
    symbol: "GOLD.PA",
    name: "Amundi Physical Gold ETC",
    price: 125,
    vol: 0.15,
    drift: 0.07,
    region: "Monde",
    sector: "Or",
    website: "https://www.amundietf.fr",
    description: "ETC adossé à de l'or physique stocké en coffre, qui suit le cours de l'once d'or en euros.",
  }),
  {
    symbol: "SPY",
    name: "SPDR S&P 500 ETF Trust",
    type: "ETF",
    currency: "USD",
    exchange: "NYSE Arca",
    session: "US",
    price: 665,
    vol: 0.16,
    drift: 0.1,
    divYield: 0.012,
    divMonths: Q,
    region: "États-Unis",
    sector: "Actions américaines",
    website: "https://www.ssga.com",
    description: "Le plus ancien et le plus échangé des ETF américains, répliquant l'indice S&P 500.",
  },
  {
    symbol: "QQQ",
    name: "Invesco QQQ Trust",
    type: "ETF",
    currency: "USD",
    exchange: "NASDAQ",
    session: "US",
    price: 595,
    vol: 0.21,
    drift: 0.13,
    divYield: 0.005,
    divMonths: Q,
    region: "États-Unis",
    sector: "Actions américaines",
    website: "https://www.invesco.com",
    description: "ETF répliquant l'indice Nasdaq-100 des 100 plus grandes sociétés non financières du Nasdaq.",
  },
  {
    symbol: "URTH",
    name: "iShares MSCI World ETF",
    type: "ETF",
    currency: "USD",
    exchange: "NYSE Arca",
    session: "US",
    price: 178,
    vol: 0.14,
    drift: 0.085,
    divYield: 0.015,
    divMonths: [6, 12],
    region: "Monde",
    sector: "Actions internationales",
    website: "https://www.ishares.com",
    description: "ETF américain répliquant l'indice MSCI World des pays développés.",
  },

  // ——— US sector ETFs (SPDR) ———
  ...(
    [
      ["XLK", "Technology Select Sector SPDR", 265, 0.22, 0.13, "Technology"],
      ["XLF", "Financial Select Sector SPDR", 53, 0.18, 0.09, "Financial Services"],
      ["XLV", "Health Care Select Sector SPDR", 140, 0.15, 0.06, "Healthcare"],
      ["XLY", "Consumer Discretionary Select Sector SPDR", 235, 0.2, 0.08, "Consumer Cyclical"],
      ["XLP", "Consumer Staples Select Sector SPDR", 80, 0.13, 0.05, "Consumer Defensive"],
      ["XLE", "Energy Select Sector SPDR", 88, 0.24, 0.05, "Energy"],
      ["XLI", "Industrial Select Sector SPDR", 150, 0.17, 0.08, "Industrials"],
      ["XLB", "Materials Select Sector SPDR", 90, 0.18, 0.05, "Basic Materials"],
      ["XLU", "Utilities Select Sector SPDR", 83, 0.16, 0.06, "Utilities"],
      ["XLRE", "Real Estate Select Sector SPDR", 42, 0.19, 0.04, "Real Estate"],
      ["XLC", "Communication Services Select Sector SPDR", 110, 0.2, 0.1, "Communication Services"],
    ] as const
  ).map(([symbol, name, price, vol, drift, sector]): CatalogEntry => ({
    symbol,
    name,
    type: "ETF",
    currency: "USD",
    exchange: "NYSE Arca",
    session: "US",
    price,
    vol,
    drift,
    divYield: 0.015,
    divMonths: Q,
    sector,
    region: "États-Unis",
  })),

  // ——— Crypto ———
  crypto("BTC-EUR", "Bitcoin EUR", 95000, 0.52, 0.2),
  crypto("ETH-EUR", "Ethereum EUR", 3600, 0.68, 0.15),
  crypto("SOL-EUR", "Solana EUR", 175, 0.85, 0.15),
  crypto("BTC-USD", "Bitcoin USD", 111000, 0.52, 0.2),
  crypto("ETH-USD", "Ethereum USD", 4200, 0.68, 0.15),

  // ——— Indices ———
  index({ symbol: "^FCHI", name: "CAC 40", currency: "EUR", session: "EU", price: 7900, vol: 0.16, drift: 0.04, region: "France" }),
  index({
    symbol: "^STOXX50E",
    name: "Euro Stoxx 50",
    currency: "EUR",
    session: "EU",
    price: 5450,
    vol: 0.16,
    drift: 0.05,
    region: "Zone euro",
  }),
  index({ symbol: "^GDAXI", name: "DAX", currency: "EUR", session: "EU", price: 24000, vol: 0.17, drift: 0.07, region: "Allemagne" }),
  index({ symbol: "^FTSE", name: "FTSE 100", currency: "GBP", session: "UK", price: 9300, vol: 0.13, drift: 0.04, region: "Royaume-Uni" }),
  index({ symbol: "^GSPC", name: "S&P 500", currency: "USD", session: "US", price: 6650, vol: 0.16, drift: 0.09, region: "États-Unis" }),
  index({
    symbol: "^IXIC",
    name: "Nasdaq Composite",
    currency: "USD",
    session: "US",
    price: 22400,
    vol: 0.21,
    drift: 0.11,
    region: "États-Unis",
  }),
  index({ symbol: "^NDX", name: "Nasdaq 100", currency: "USD", session: "US", price: 24500, vol: 0.21, drift: 0.12, region: "États-Unis" }),
  index({
    symbol: "^DJI",
    name: "Dow Jones Industrial Average",
    currency: "USD",
    session: "US",
    price: 46300,
    vol: 0.14,
    drift: 0.07,
    region: "États-Unis",
  }),
  index({ symbol: "^N225", name: "Nikkei 225", currency: "JPY", session: "JP", price: 45000, vol: 0.2, drift: 0.07, region: "Japon" }),
  index({ symbol: "^HSI", name: "Hang Seng", currency: "HKD", session: "HK", price: 26000, vol: 0.23, drift: 0.02, region: "Hong Kong" }),
  index({
    symbol: "^VIX",
    name: "VIX (volatilité S&P 500)",
    currency: "USD",
    session: "US",
    price: 16,
    vol: 0.8,
    drift: 0,
    region: "États-Unis",
  }),
  index({ symbol: "^TNX", name: "Taux US 10 ans", currency: "USD", session: "US", price: 4.15, vol: 0.25, drift: 0, region: "États-Unis" }),

  // ——— Currencies ———
  fx("EURUSD=X", "Euro / Dollar US", 1.17),
  fx("EURGBP=X", "Euro / Livre sterling", 0.87),
  fx("EURCHF=X", "Euro / Franc suisse", 0.935),
  fx("EURJPY=X", "Euro / Yen", 172),
  fx("USDJPY=X", "Dollar US / Yen", 147),
  fx("GBPUSD=X", "Livre sterling / Dollar US", 1.345),

  // ——— Commodities ———
  future("GC=F", "Or (once)", 3650, 0.15),
  future("SI=F", "Argent (once)", 42, 0.28),
  future("BZ=F", "Pétrole Brent", 67, 0.32),
  future("CL=F", "Pétrole WTI", 63, 0.34),
  future("NG=F", "Gaz naturel", 3.1, 0.55),
  future("HG=F", "Cuivre", 4.6, 0.22),
];

export const CATALOG_BY_SYMBOL: Record<string, CatalogEntry> = Object.fromEntries(CATALOG.map((e) => [e.symbol, e]));

export function catalogEntry(symbol: string): CatalogEntry | undefined {
  return CATALOG_BY_SYMBOL[symbol];
}

/** Reference value of one unit of each currency, expressed in euros (simulator anchor). */
export const EUR_PER_UNIT: Record<string, number> = {
  EUR: 1,
  USD: 1 / 1.17,
  GBP: 1 / 0.87,
  CHF: 1 / 0.935,
  JPY: 1 / 172,
  DKK: 0.134,
  SEK: 0.091,
  NOK: 0.085,
  HKD: 0.11,
  CAD: 0.62,
  AUD: 0.56,
  CNY: 0.12,
  KRW: 0.00062,
  INR: 0.0097,
  BRL: 0.16,
  ZAR: 0.048,
  ILS: 0.25,
};

export const INDEX_SYMBOLS = ["^FCHI", "^STOXX50E", "^GDAXI", "^FTSE", "^GSPC", "^IXIC", "^DJI", "^N225", "^HSI"];
export const FX_SYMBOLS = ["EURUSD=X", "EURGBP=X", "EURCHF=X", "EURJPY=X", "USDJPY=X", "GBPUSD=X"];
export const COMMODITY_SYMBOLS = ["GC=F", "SI=F", "BZ=F", "CL=F", "NG=F", "HG=F"];
export const CRYPTO_SYMBOLS = ["BTC-EUR", "ETH-EUR", "SOL-EUR"];
export const RATE_SYMBOLS = ["^TNX", "^VIX"];
export const SECTOR_ETFS = ["XLK", "XLF", "XLV", "XLY", "XLP", "XLE", "XLI", "XLB", "XLU", "XLRE", "XLC"];
/** Approximate weight of each sector in the S&P 500 (tile sizes only). */
export const SECTOR_WEIGHTS: Record<string, number> = {
  XLK: 32,
  XLF: 13,
  XLV: 10,
  XLY: 10,
  XLC: 9,
  XLI: 8,
  XLP: 6,
  XLE: 3.5,
  XLU: 2.5,
  XLRE: 2.2,
  XLB: 2,
};

export interface Benchmark {
  symbol: string;
  label: string;
  description: string;
}

/** Benchmarks offered for comparisons. Accumulating ETFs reinvest dividends (total return). */
export const BENCHMARKS: Benchmark[] = [
  { symbol: "CW8.PA", label: "MSCI World", description: "Amundi MSCI World (EUR, dividendes réinvestis)" },
  { symbol: "ESE.PA", label: "S&P 500", description: "BNP Easy S&P 500 (EUR, dividendes réinvestis)" },
  { symbol: "PANX.PA", label: "Nasdaq-100", description: "Amundi PEA Nasdaq-100 (EUR, dividendes réinvestis)" },
  { symbol: "^FCHI", label: "CAC 40", description: "Indice CAC 40 (hors dividendes)" },
  { symbol: "^STOXX50E", label: "Euro Stoxx 50", description: "Indice Euro Stoxx 50 (hors dividendes)" },
  { symbol: "PAEEM.PA", label: "Émergents", description: "Amundi PEA MSCI Emerging Markets (EUR)" },
  { symbol: "GC=F", label: "Or", description: "Once d'or (converti en EUR)" },
  { symbol: "BTC-EUR", label: "Bitcoin", description: "Bitcoin en euros" },
];

export const DEFAULT_BENCHMARK = "CW8.PA";

const SECTOR_FR: Record<string, string> = {
  Technology: "Technologie",
  "Financial Services": "Services financiers",
  Healthcare: "Santé",
  "Consumer Cyclical": "Consommation cyclique",
  "Consumer Defensive": "Consommation de base",
  Industrials: "Industrie",
  Energy: "Énergie",
  Utilities: "Services aux collectivités",
  "Real Estate": "Immobilier",
  "Basic Materials": "Matériaux",
  "Communication Services": "Communication",
  realestate: "Immobilier",
  consumer_cyclical: "Consommation cyclique",
  basic_materials: "Matériaux",
  consumer_defensive: "Consommation de base",
  technology: "Technologie",
  communication_services: "Communication",
  financial_services: "Services financiers",
  utilities: "Services aux collectivités",
  industrials: "Industrie",
  energy: "Énergie",
  healthcare: "Santé",
};

export function sectorLabel(sector: string | undefined | null): string {
  if (!sector) return "Non classé";
  return SECTOR_FR[sector] ?? sector;
}

const COUNTRY_FR: Record<string, string> = {
  "United States": "États-Unis",
  France: "France",
  Netherlands: "Pays-Bas",
  Germany: "Allemagne",
  Switzerland: "Suisse",
  "United Kingdom": "Royaume-Uni",
  Denmark: "Danemark",
  Italy: "Italie",
  Spain: "Espagne",
  Ireland: "Irlande",
  Japan: "Japon",
  China: "Chine",
  "Hong Kong": "Hong Kong",
  Taiwan: "Taïwan",
  "South Korea": "Corée du Sud",
  Canada: "Canada",
  Belgium: "Belgique",
  Sweden: "Suède",
  Norway: "Norvège",
  Finland: "Finlande",
  Luxembourg: "Luxembourg",
  Australia: "Australie",
  India: "Inde",
  Brazil: "Brésil",
  Israel: "Israël",
  Portugal: "Portugal",
  Austria: "Autriche",
  Singapore: "Singapour",
  Uruguay: "Uruguay",
  Bermuda: "Bermudes",
  "Cayman Islands": "Îles Caïmans",
  Jersey: "Jersey",
};

export function countryLabel(country: string | undefined | null): string {
  if (!country) return "Non renseigné";
  return COUNTRY_FR[country] ?? country;
}

/** Best-effort exposure region of a fund from its name. */
export function regionFromName(name: string): string | undefined {
  const n = name.toLowerCase();
  if (/(all[- ]world|acwi|monde|world|global)/.test(n)) return "Monde";
  if (/(emerging|émergent|emergents|\bem\b)/.test(n)) return "Pays émergents";
  if (/(s&p|nasdaq|dow jones|russell|\bus\b|usa|america)/.test(n)) return "États-Unis";
  if (/(cac|france)/.test(n)) return "France";
  if (/(stoxx|europe|euro|emu)/.test(n)) return "Europe";
  if (/(japan|japon|nikkei|topix)/.test(n)) return "Japon";
  if (/(china|chine|hang seng)/.test(n)) return "Chine";
  if (/(india|inde)/.test(n)) return "Inde";
  if (/(gold|\bor\b|physical)/.test(n)) return "Monde";
  return undefined;
}

const TYPE_FR: Record<AssetType, string> = {
  EQUITY: "Actions",
  ETF: "ETF",
  CRYPTOCURRENCY: "Crypto-actifs",
  INDEX: "Indices",
  CURRENCY: "Devises",
  MUTUALFUND: "Fonds",
  FUTURE: "Matières premières",
  OTHER: "Autres",
};

export function assetTypeLabel(type: AssetType | undefined): string {
  return TYPE_FR[type ?? "OTHER"] ?? "Autres";
}

function normalizeText(text: string) {
  return text.normalize("NFD").replace(/[̀-ͯ]/g, "").toLowerCase();
}

/** Offline search over the catalog (symbol prefix first, then name matches). */
export function searchCatalog(query: string, limit = 12): CatalogEntry[] {
  const q = normalizeText(query.trim());
  if (!q) return [];
  const scored: { entry: CatalogEntry; score: number }[] = [];
  for (const entry of CATALOG) {
    const sym = entry.symbol.toLowerCase();
    const name = normalizeText(entry.name);
    let score = 0;
    if (sym === q) score = 100;
    else if (sym.startsWith(q)) score = 80;
    else if (name.startsWith(q)) score = 70;
    else if (name.includes(q)) score = 50;
    else if (sym.includes(q)) score = 40;
    if (score > 0) scored.push({ entry, score });
  }
  return scored
    .sort((a, b) => b.score - a.score || a.entry.symbol.localeCompare(b.entry.symbol))
    .slice(0, limit)
    .map((s) => s.entry);
}
